name: asco
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.3.3 <4.0.0"

dependencies:
  after_layout: ^1.2.0
  cached_network_image: ^3.3.1
  equatable: ^2.0.5
  file_picker: ^8.0.3
  flutter:
    sdk: flutter
  flutter_form_builder: ^9.2.1
  flutter_localizations:
    sdk: flutter
  flutter_markdown: ^0.7.1
  flutter_rating_bar: ^4.0.1
  flutter_riverpod: ^2.5.1
  flutter_spinkit: ^5.2.1
  flutter_svg: ^2.0.10+1
  form_builder_validators: ^9.1.0
  http: ^1.2.1
  image_cropper: ^6.0.0
  image_picker: ^1.1.1
  internet_connection_checker: ^1.0.0+1
  intl: any
  markdown_editable_textinput: ^2.1.0
  open_file_plus: ^3.4.1+1
  path: ^1.9.0
  path_provider: ^2.1.3
  rive: ^0.13.5
  riverpod_annotation: ^2.3.5
  shared_preferences: ^2.2.3

dev_dependencies:
  build_runner: ^2.4.9
  custom_lint: ^0.6.4
  flutter_launcher_icons: ^0.13.1
  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter
  import_sorter: ^4.6.0
  riverpod_generator: ^2.4.0
  riverpod_lint: ^2.3.10

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/icons/
    - assets/images/
    - assets/rive_animations/
    - assets/vectors/

  fonts:
    - family: Poppins
      fonts:
        - asset: fonts/Poppins-Bold.ttf
        - asset: fonts/Poppins-SemiBold.ttf
        - asset: fonts/Poppins-Medium.ttf
        - asset: fonts/Poppins-Regular.ttf
        - asset: fonts/Poppins-Light.ttf
